### PR TITLE
François One update

### PR DESCRIPTION
**Pull request by emmamarichal**
Hi @Fonthausen,

I reviewed your update, it's really nice! 
Here you can find the QA: [QA_FrançoisOne.zip](https://github.com/Fonthausen/francoisoneFont/files/10744405/QA_FrancoisOne.zip)

Excepted few things like adding 'notdef' or adding kerning to caron glyphs, all is good!

We have the same problem as before concerning repos and synchronisation, could you after merging this, send a PR to https://github.com/googlefonts/francoisoneFont? Thanks! :)

Have a nice day,
Emma

### CODE REVIEW

**Comment by Fonthausen** [comment]
@emmamarichal  You want me to have a look at the caron kerning ?

**Comment by emmamarichal** [comment]
Capture d’écran 2023-02-15 à 16 26 47

Sure, this is what I added, tell me if it's ok for you!

**Comment by Fonthausen** [comment]
@emmamarichal It's super ! Sorry I missed it

**Comment by emmamarichal** [comment]
No problem! :)

**Comment by emmamarichal** [comment]
@Fonthausen Could you tell me when you have sent a PR to the Google repo? I don't have access, so I'd have to tell my colleagues to merge

**Comment by Fonthausen** [comment]
@emmamarichal You mean this ?

Schermafbeelding 2023-02-16 om 14 25 31

**Comment by emmamarichal** [comment]
Yes, like you did last time with Paytone: https://github.com/googlefonts/paytoneFont/pull/4
Thanks!

**Comment by emmamarichal** [comment]
https://github.com/googlefonts/francoisoneFont

**Pull request merged**
